set -g default-terminal "tmux-256color"
set-option -a terminal-features 'xterm-256color:RGB'
set -g mode-keys vi
set -g automatic-rename on
set -g renumber-windows off

set -g status-style fg=#272E33,bg=#A7C080
set -g pane-border-style fg=#A7C080
set -g pane-active-border-style fg=#E67E80
set -g history-limit 10000

unbind C-b
set -g prefix `
bind-key ` send-prefix

bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key h clear-history

unbind-key -T copy-mode-vi 'v'
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection
bind-key j run-shell tmux_select_pane.sh
